### ISSUE TITLE
Slackbotのメッセージが移行できない？

### ISSUE THREAD

**Issue by nandenjin** [revoltage-inc/msd-cli#132]
### Bug content 

`migrate:message` の実行時に以下のエラーが発生しました。

```
$ npm run migrate:message

> msd-cli@1.3.1 migrate:message
> node --loader ts-node/esm ./command/migrate/message.mts

(node:2387) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✔️ Create client
× Migrate message
Error: An API error occurred: bot_not_found
    at platformErrorFromResult (/home/nandenjin/workspace/msd-cli/node_modules/@slack/web-api/src/errors.ts:95:5)
    at WebClient.apiCall (/home/nandenjin/workspace/msd-cli/node_modules/@slack/web-api/src/WebClient.ts:263:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserClient.getBot (file:///home/nandenjin/workspace/msd-cli/libs/user.mts:166:20)
    at async MessageClient.migrateAllMessage (file:///home/nandenjin/workspace/msd-cli/libs/message.mts:119:22)
    at async file:///home/nandenjin/workspace/msd-cli/command/migrate/message.mts:61:5 {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'bot_not_found',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

調べたところ、エラーを吐いているのはIDが`B01`で、Slackbotのメッセージ（リマインダーなど）のようです。

Slack APIは`B01`に対する`bots.info`呼び出しに対応していないように思われます。
https://github.com/slackapi/python-slack-sdk/issues/1260

### How to reproduce bug 

以下のようなメッセージを含むバックアップファイルを入力とすることで再現します。

```json
{
        "bot_id": "B01",
        "type": "message",
        "text": "リマインダー : リマインダーの内容",
        "user": "USLACKBOT",
        "ts": "1581030006.000100",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "eYVsW",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "リマインダー : リマインダーの内容"
                            }
                        ]
                    }
                ]
            }
        ],
        "team": "XXXXXX"
    }
```

### How to fix

`user.getBot()` で、`B01`に対して（Slack APIをコールせず）ダミーレスポンスを返すようにすることで正常に動作しました。

**Comment by nandenjin** [comment]
#58 のDuplicateかもしれないですね……すみません
