### ISSUE TITLE
返信メッセージが読み込めない

### ISSUE THREAD

**Issue by take048** [revoltage-inc/msd-cli#86]
`npm run deploy:message`で
返信メッセージを読み込むと以下のようなエラーが出ます。

> Error: Failed to get thread message
Message Timestamp: 〜
Message Content: 〜
    at MessageClient.deployMessage (file:///〜/msd-cli/libs/message.mts:278:17)
    at async MessageClient.deployManyMessage (file:///〜/msd-cli/libs/message.mts:217:7)
    at async MessageClient.deployAllMessage (file:///〜/msd-cli/libs/message.mts:199:9)
    at async file:///〜/msd-cli/command/deploy/message.mts:55:5

他の返信は読み込めたのですが、一部返信でこのようなエラーが出ます。

解決のほどよろしくお願いいたします。

**Comment by yogarasu** [comment]
@take048 
おそらく#75と同じ要因だと思われます
#75 で対応中のため、クローズします

**Comment by yogarasu** [comment]
@take048 
一通りの修正を行いましたので、まだこの問題にお悩みの場合はv1.3.0をお試しください
https://github.com/revoltage-inc/msd-cli/releases/
